### ISSUE TITLE
Log format hard to read

### ISSUE THREAD

**Issue by yiv** [sunshine-protocol/frusty-logger#1]
I printed a log like below

```
info!("load_page success, len = {}", html.len());
```

Because I didn't filter the log, so many log printed

```
flutter: \^[[1;32mℹ\^[[0m \^[[32mINFO\^[[0m \^[[1mmaego_ffi\^[[0m > load_page success,<…>
flutter: \^[[1;35m🤓\^[[0m \^[[2;35mTRACE\^[[0m \^[[1mhyper::proto::h1::dispatch\^[[0m > clien<…>
flutter: \^[[1;35m🤓\^[[0m \^[[2;35mTRACE\^[[0m \^[[1mhyper::proto::h1::conn\^[[0m > State::c<…>
flutter: \^[[1;35m🤓\^[[0m \^[[2;35mTRACE\^[[0m \^[[1mhyper::proto::h1::conn\^[[0m > State::cl<…>
flutter: \^[[1;35m🤓\^[[0m \^[[2;35mTRACE\^[[0m \^[[1mhyper::proto::h1::conn\^[[0m > flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive:<…>
flutter: \^[[1;35m🤓\^[[0m \^[[2;35mTRACE\^[[0m \^[[1mhyper::proto::h1::conn\^[[0m > shut down <…>
flutter: \^[[1;35m🤓\^[[0m \^[[2;35mTRACE\^[[0m \^[[1mmio::poll\^[[0m > deregistering handle<…>
flutter: \^[[1;35m🤓\^[[0m \^[[2;35mTRACE\^[[0m \^[[1mwant\^[[0m > si<…>
```

But this line should print out the length of success response of **load_page**, looks like more log after **load_page success** have been omitd

```
flutter: \^[[1;32mℹ\^[[0m \^[[32mINFO\^[[0m \^[[1mmaego_ffi\^[[0m > load_page success,<…>
```

All logs are hard to read. Is there any config need to be setted to make logs more readable

**Comment by shekohex** [comment]
I guess your Terminal dose not support ASCII colors? or you been using VSCode Debugging console maybe.
Anyway, to filter the logs, this should be done in the Rust side as following:
```rust
frusty_logger::include_ffi!(
  with_config: Config::new(
    Level::Debug, // minimum log level
    FilterBuilder::new()
    .parse(&[
      "sunshine", // should be your rust crate name
      "sunshine-identity-ffi",
      // .. other crates here too if you are interested. 
      ].join(",") // join all entries by ',' to build up the string.
    )
    .build()
  )
);
```

I guess I should add an option to disable colors using the config.
Btw if you tried to run the app using for example macOS terminal or Windows Terminal (any linux terminal works too) by typing `flutter run` you should see a colorful logs.

**Comment by yiv** [comment]
The system I am using is macOS, it looks like that the IDEA build console doesn't support ACII colors, I switch to terminal and run **flutter run**, the log format works fine and looks beautiful.

Thanks a lot.

**Comment by yiv** [comment]
Sorrry for my previous arbitary conclusion. I delete my last comment and reopen this issue.

The system I am using is macOS, the logs quoted in this issue earlier is from the output of IDEA BUILD, then I switch to macOS terminal (zsh), they are displaying like below:

```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:56078/4UY_QoLcqeo=/
flutter: edwin 522021-01-11 10:46:19.124845
flutter: edwin 552021-01-11 10:46:24.138246
flutter: \^[[1;32mℹ\^[[0m \^[[32mINFO\^[[0m \^[[1mmaego_ffi\^[[0m > frusty<…>
flutter: \^[[1;31m❌\^[[0m \^[[1;4;31mERROR\^[[0m \^[[1mmaego_ffi\^[[0m > ch<…>
flutter: nativeLoop: 1
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Bad state: channel closed
#0      Maego.getPicFrame (package:maego_ffi/maego_ffi.dart:37:7)
<asynchronous suspension>
#1      _MyHomePageState._showWebPage (package:maego/main.dart:71:30)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
#10     GestureBinding.dispatchEvent (package<…>
```

The logs below is from rust:
```
flutter: \^[[1;32mℹ\^[[0m \^[[32mINFO\^[[0m \^[[1mmaego_ffi\^[[0m > frusty<…>
flutter: \^[[1;31m❌\^[[0m \^[[1;4;31mERROR\^[[0m \^[[1mmaego_ffi\^[[0m > ch<…>
```

Thanks a lot for your reply. Right now I know it's the matter about the ANSI terminal color painting. Maybe there some wrong with my zsh, I will check that out.

**Comment by vidorge** [comment]
Hey guys, any info on how to display the whole log line? I am having problems with the last part of the log being abbreviated and not showing the actual string that was logged:

```rust
log::error!("test123 {}", 42);
```

```
flutter: \^[[1;31m❌\^[[0m \^[[1;4;31mERROR\^[[0m \^[[1mscrap\^[[0m <…>
```
--------------------------------------------------------------------------------^^^^

Using zsh, iOS

**Comment by yiv** [comment]
Right now, I forked the repository and disabled it

**Comment by shekohex** [comment]
Hi, @yiv could you please open a PR for this? I will happily accept it :)

**Comment by yiv** [comment]
I just brutally disabled it, let me do some work to make it configurable
